spring:
  application:
    name: reactive_application

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/spring_reactive
    user: postgres
    password: postgres

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: postgres